name: quote_app
description: Quote App using dummyjson quotes
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  share_plus: ^6.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
