name: quote_app
description: Quote App using dummy's quotes
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  share_plus: ^9.0.0
  intl: ^0.18.1
  get: ^4.7.2
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit-Italic.ttf
          style: italic
        - asset: assets/fonts/Kanit-BoldItalic.ttf
          weight: 700
          style: italic
